//! Request handlers.
//!
//! Each submodule provides async handler functions for a single resource.
//! Handlers delegate to the corresponding repository in `trulience_db`
//! and map errors via [`AppError`].

pub mod admin;
pub mod api_keys;
pub mod approval;
pub mod assets;
pub mod audit;
pub mod auth;
pub mod bug_reports;
pub mod character;
pub mod character_metadata;
pub mod checkpoints;
pub mod collaboration;
pub mod config_export;
pub mod dashboard;
pub mod derived_image;
pub mod embedding;
pub mod extensions;
pub mod hardware;
pub mod image_qa;
pub mod image_variant;
pub mod importer;
pub mod job_debug;
pub mod jobs;
pub mod keymaps;
pub mod layouts;
pub mod library;
pub mod metadata;
pub mod notification;
pub mod onboarding;
pub mod palette;
pub mod performance;
pub mod proficiency;
pub mod project;
pub mod queue;
pub mod reclamation;
pub mod review_notes;
pub mod scene;
pub mod scene_type;
pub mod scene_video_version;
pub mod scripts;
pub mod search;
pub mod segment;
pub mod source_image;
pub mod storage;
pub mod tags;
pub mod themes;
pub mod trash;
pub mod undo_tree;
pub mod validation;
pub mod video;
pub mod webhooks;
pub mod workflow_canvas;
pub mod workers;
pub mod workspace;
