//! Clip QA (quality assurance) review status constants and helpers (PRD-121).
//!
//! These represent the human review status of a scene video version clip,
//! distinct from the score-level QA status in `qa_status.rs` (pass/warn/fail).

use crate::error::CoreError;

// ---------------------------------------------------------------------------
// Review status constants
// ---------------------------------------------------------------------------

/// Clip has not been reviewed.
pub const CLIP_QA_PENDING: &str = "pending";

/// Clip was approved by a reviewer.
pub const CLIP_QA_APPROVED: &str = "approved";

/// Clip was rejected by a reviewer.
pub const CLIP_QA_REJECTED: &str = "rejected";

/// All valid clip QA statuses.
pub const VALID_CLIP_QA_STATUSES: &[&str] = &[CLIP_QA_PENDING, CLIP_QA_APPROVED, CLIP_QA_REJECTED];

// ---------------------------------------------------------------------------
// Source constants
// ---------------------------------------------------------------------------

/// Clip source: generated by the pipeline.
pub const CLIP_SOURCE_GENERATED: &str = "generated";

/// Clip source: imported by a user.
pub const CLIP_SOURCE_IMPORTED: &str = "imported";

// ---------------------------------------------------------------------------
// Resume status
// ---------------------------------------------------------------------------

/// Status returned when a resume-from operation is ready for generation.
pub const RESUME_STATUS_READY: &str = "ready_to_generate";

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/// Validate that `status` is a valid clip QA review status.
pub fn validate_clip_qa_status(status: &str) -> Result<(), CoreError> {
    if VALID_CLIP_QA_STATUSES.contains(&status) {
        Ok(())
    } else {
        Err(CoreError::Validation(format!(
            "Invalid clip QA status '{status}'. Must be one of: {VALID_CLIP_QA_STATUSES:?}"
        )))
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_valid_statuses() {
        assert!(validate_clip_qa_status("pending").is_ok());
        assert!(validate_clip_qa_status("approved").is_ok());
        assert!(validate_clip_qa_status("rejected").is_ok());
    }

    #[test]
    fn validate_invalid_status() {
        assert!(validate_clip_qa_status("pass").is_err());
        assert!(validate_clip_qa_status("").is_err());
    }
}
