//! Image management constants and validation (PRD-21).

/// Supported image file formats for source images and variants.
pub const VALID_IMAGE_FORMATS: &[&str] = &["png", "jpeg", "jpg", "webp"];

/// Provenance value for images generated by ComfyUI workflows.
pub const PROVENANCE_GENERATED: &str = "generated";

/// Provenance value for images that were exported, edited externally, and re-imported.
pub const PROVENANCE_MANUALLY_EDITED: &str = "manually_edited";

/// Provenance value for images uploaded directly by a user (not generated).
pub const PROVENANCE_MANUAL_UPLOAD: &str = "manual_upload";

/// Validate that the given format string is a supported image format.
///
/// The check is case-insensitive.
///
/// # Examples
///
/// ```
/// use x121_core::images::is_valid_image_format;
///
/// assert!(is_valid_image_format("png"));
/// assert!(is_valid_image_format("JPEG"));
/// assert!(!is_valid_image_format("gif"));
/// ```
pub fn is_valid_image_format(format: &str) -> bool {
    let lower = format.to_lowercase();
    VALID_IMAGE_FORMATS.contains(&lower.as_str())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn valid_formats_accepted() {
        for fmt in VALID_IMAGE_FORMATS {
            assert!(is_valid_image_format(fmt), "Expected {fmt} to be valid");
        }
    }

    #[test]
    fn case_insensitive_check() {
        assert!(is_valid_image_format("PNG"));
        assert!(is_valid_image_format("Jpeg"));
        assert!(is_valid_image_format("WebP"));
    }

    #[test]
    fn invalid_formats_rejected() {
        assert!(!is_valid_image_format("gif"));
        assert!(!is_valid_image_format("bmp"));
        assert!(!is_valid_image_format("tiff"));
        assert!(!is_valid_image_format(""));
    }

    #[test]
    fn provenance_constants_are_distinct() {
        let all = [
            PROVENANCE_GENERATED,
            PROVENANCE_MANUALLY_EDITED,
            PROVENANCE_MANUAL_UPLOAD,
        ];
        for (i, a) in all.iter().enumerate() {
            for (j, b) in all.iter().enumerate() {
                if i != j {
                    assert_ne!(a, b);
                }
            }
        }
    }
}
