//! Image management constants and validation (PRD-21).

use std::io::Cursor;

/// Supported image file formats for source images and variants.
pub const VALID_IMAGE_FORMATS: &[&str] = &["png", "jpeg", "jpg", "webp"];

/// Provenance value for images generated by ComfyUI workflows.
pub const PROVENANCE_GENERATED: &str = "generated";

/// Provenance value for images that were exported, edited externally, and re-imported.
pub const PROVENANCE_MANUALLY_EDITED: &str = "manually_edited";

/// Provenance value for images uploaded directly by a user (not generated).
pub const PROVENANCE_MANUAL_UPLOAD: &str = "manual_upload";

/// Validate that the given format string is a supported image format.
///
/// The check is case-insensitive.
///
/// # Examples
///
/// ```
/// use x121_core::images::is_valid_image_format;
///
/// assert!(is_valid_image_format("png"));
/// assert!(is_valid_image_format("JPEG"));
/// assert!(!is_valid_image_format("gif"));
/// ```
pub fn is_valid_image_format(format: &str) -> bool {
    let lower = format.to_lowercase();
    VALID_IMAGE_FORMATS.contains(&lower.as_str())
}

/// Extract image dimensions (width, height) from raw bytes.
///
/// Uses header-only parsing — does not decode the full pixel data.
/// Returns `None` if the format is unrecognised or the header is corrupt.
pub fn image_dimensions(data: &[u8]) -> Option<(u32, u32)> {
    let reader = image::ImageReader::new(Cursor::new(data))
        .with_guessed_format()
        .ok()?;
    reader.into_dimensions().ok()
}

/// Generate a JPEG thumbnail from raw image bytes.
///
/// Resizes the image so the longest edge is at most `max_edge` pixels,
/// preserving aspect ratio. Returns JPEG bytes at quality 80.
/// Returns `None` if the image cannot be decoded.
pub fn generate_thumbnail(data: &[u8], max_edge: u32) -> Option<Vec<u8>> {
    let reader = image::ImageReader::new(Cursor::new(data))
        .with_guessed_format()
        .ok()?;
    let img = reader.decode().ok()?;
    let thumb = img.thumbnail(max_edge, max_edge);
    let mut buf = Vec::new();
    let encoder = image::codecs::jpeg::JpegEncoder::new_with_quality(&mut buf, 80);
    thumb.write_with_encoder(encoder).ok()?;
    Some(buf)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn valid_formats_accepted() {
        for fmt in VALID_IMAGE_FORMATS {
            assert!(is_valid_image_format(fmt), "Expected {fmt} to be valid");
        }
    }

    #[test]
    fn case_insensitive_check() {
        assert!(is_valid_image_format("PNG"));
        assert!(is_valid_image_format("Jpeg"));
        assert!(is_valid_image_format("WebP"));
    }

    #[test]
    fn invalid_formats_rejected() {
        assert!(!is_valid_image_format("gif"));
        assert!(!is_valid_image_format("bmp"));
        assert!(!is_valid_image_format("tiff"));
        assert!(!is_valid_image_format(""));
    }

    #[test]
    fn image_dimensions_returns_none_for_garbage() {
        assert!(image_dimensions(b"not an image").is_none());
        assert!(image_dimensions(&[]).is_none());
    }

    #[test]
    fn image_dimensions_parses_minimal_png() {
        // Minimal 1x1 white PNG (67 bytes)
        let png: &[u8] = &[
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG sig
            0x00, 0x00, 0x00, 0x0D, // IHDR length
            0x49, 0x48, 0x44, 0x52, // "IHDR"
            0x00, 0x00, 0x00, 0x01, // width=1
            0x00, 0x00, 0x00, 0x01, // height=1
            0x08, 0x02, // 8-bit RGB
            0x00, 0x00, 0x00, // compression, filter, interlace
            0x90, 0x77, 0x53, 0xDE, // IHDR CRC
            0x00, 0x00, 0x00, 0x0C, // IDAT length
            0x49, 0x44, 0x41, 0x54, // "IDAT"
            0x08, 0xD7, 0x63, 0xF8, 0xCF, 0xC0, 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0xE2, 0x21,
            0xBC, 0x33, // IDAT CRC
            0x00, 0x00, 0x00, 0x00, // IEND length
            0x49, 0x45, 0x4E, 0x44, // "IEND"
            0xAE, 0x42, 0x60, 0x82, // IEND CRC
        ];
        let dims = image_dimensions(png);
        assert_eq!(dims, Some((1, 1)));
    }

    #[test]
    fn provenance_constants_are_distinct() {
        let all = [
            PROVENANCE_GENERATED,
            PROVENANCE_MANUALLY_EDITED,
            PROVENANCE_MANUAL_UPLOAD,
        ];
        for (i, a) in all.iter().enumerate() {
            for (j, b) in all.iter().enumerate() {
                if i != j {
                    assert_ne!(a, b);
                }
            }
        }
    }
}
