-- Scene video version tracking (PRD-109 Req 1.1)
-- Tracks every video produced for a scene — generated by pipeline or imported externally.

CREATE TABLE scene_video_versions (
    id              BIGSERIAL PRIMARY KEY,
    scene_id        BIGINT NOT NULL REFERENCES scenes(id) ON DELETE CASCADE ON UPDATE CASCADE,
    version_number  INTEGER NOT NULL,
    source          TEXT NOT NULL CHECK (source IN ('generated', 'imported')),
    file_path       TEXT NOT NULL,
    file_size_bytes BIGINT,
    duration_secs   NUMERIC(10,3),
    is_final        BOOLEAN NOT NULL DEFAULT false,
    notes           TEXT,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on row change
CREATE TRIGGER set_updated_at_scene_video_versions
    BEFORE UPDATE ON scene_video_versions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Unique version number per scene
CREATE UNIQUE INDEX uq_scene_video_versions_scene_version
    ON scene_video_versions (scene_id, version_number);

-- At most one final version per scene (only among non-deleted rows)
CREATE UNIQUE INDEX uq_scene_video_versions_final
    ON scene_video_versions (scene_id)
    WHERE is_final = true AND deleted_at IS NULL;

-- FK index for scene_id lookups
CREATE INDEX idx_scene_video_versions_scene_id
    ON scene_video_versions (scene_id);

-- Soft-delete filter index
CREATE INDEX idx_scene_video_versions_deleted_at
    ON scene_video_versions (deleted_at)
    WHERE deleted_at IS NOT NULL;
